services:
  chproxy:
    image: tacyuuhon/clickhouse-chproxy:latest
    ports:
      - 9050:9090
    volumes:
      - ./chproxy/config.yml:/opt/config.yml:ro
    depends_on:
      - ch-01-01
      - ch-01-02
      - ch-02-01
      - ch-02-02

  zookeeper-1:
    image: zookeeper:3.5
    volumes:
      - ./data/zookeeper:/data
      - ./data/zookeeper-log:/datalog
    environment:
      ZOO_AUTOPURGE_PURGEINTERVAL: 1
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=toxiproxy:3011:3012;3010 server.2=toxiproxy:3014:3015;3013 server.3=toxiproxy:3017:3018;3016
    depends_on:
      - toxiproxy

  zookeeper-2:
    image: zookeeper:3.5
    volumes:
      - ./data/zookeeper:/data
      - ./data/zookeeper-log:/datalog
    environment:
      ZOO_AUTOPURGE_PURGEINTERVAL: 1
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=toxiproxy:3011:3012;3010 server.2=toxiproxy:3014:3015;3013 server.3=toxiproxy:3017:3018;3016
    depends_on:
      - toxiproxy

  zookeeper-3:
    image: zookeeper:3.5
    volumes:
      - ./data/zookeeper:/data
      - ./data/zookeeper-log:/datalog
    environment:
      ZOO_AUTOPURGE_PURGEINTERVAL: 1
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=toxiproxy:3011:3012;3010 server.2=toxiproxy:3014:3015;3013 server.3=toxiproxy:3017:3018;3016
    depends_on:
      - toxiproxy

  ch-01-01:
    image: yandex/clickhouse-server:21.4.5-alpine
    hostname: ch-01-01
    volumes:
      - ./data/clickhouse/ch-01-01/:/var/lib/clickhouse
      - ./clickhouse/initdb.d/:/docker-entrypoint-initdb.d:ro
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml:ro
      - ./clickhouse/config.d/ch-01-01.xml:/etc/clickhouse-server/config.d/node-config.xml:ro
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  ch-01-02:
    image: yandex/clickhouse-server:21.4.5-alpine
    hostname: ch-01-02
    volumes:
      - ./data/clickhouse/ch-01-02/:/var/lib/clickhouse
      - ./clickhouse/initdb.d/:/docker-entrypoint-initdb.d:ro
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml:ro
      - ./clickhouse/config.d/ch-01-02.xml:/etc/clickhouse-server/config.d/node-config.xml:ro
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  ch-02-01:
    image: yandex/clickhouse-server:21.4.5-alpine
    hostname: ch-02-01
    volumes:
      - ./data/clickhouse/ch-02-01/:/var/lib/clickhouse
      - ./clickhouse/initdb.d/:/docker-entrypoint-initdb.d:ro
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml:ro
      - ./clickhouse/config.d/ch-02-01.xml:/etc/clickhouse-server/config.d/node-config.xml:ro
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  ch-02-02:
    image: yandex/clickhouse-server:21.4.5-alpine
    hostname: ch-02-02
    volumes:
      - ./data/clickhouse/ch-02-02/:/var/lib/clickhouse
      - ./clickhouse/initdb.d/:/docker-entrypoint-initdb.d:ro
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml:ro
      - ./clickhouse/config.d/ch-02-02.xml:/etc/clickhouse-server/config.d/node-config.xml:ro
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  toxiproxy:
    image: "ghcr.io/shopify/toxiproxy"
    entrypoint: > 
      sh -c "/go/bin/toxiproxy-cli -h toxiproxy:8474 create zookeeper-1-cl --listen 0.0.0.0:3010 --upstream zookeeper-1:2181;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create zookeeper-1-le --listen 0.0.0.0:3011 --upstream zookeeper-1:2888;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create zookeeper-1-sync --listen 0.0.0.0:3012 --upstream zookeeper-1:3888;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create zookeeper-2-cl --listen 0.0.0.0:3013 --upstream zookeeper-2:2181;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create zookeeper-2-le --listen 0.0.0.0:3014 --upstream zookeeper-2:2888;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create zookeeper-2-sync --listen 0.0.0.0:3015 --upstream zookeeper-2:3888;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create zookeeper-3-cl --listen 0.0.0.0:3016 --upstream zookeeper-3:2181
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create zookeeper-3-le --listen 0.0.0.0:3017 --upstream zookeeper-3:2888;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create zookeeper-3-sync --listen 0.0.0.0:3018 --upstream zookeeper-3:3888;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create ch-01-01-cl --listen 0.0.0.0:3019 --upstream ch-01-01:8123;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create ch-01-01-sync --listen 0.0.0.0:3020 --upstream ch-01-01:9000;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create ch-01-02-cl --listen 0.0.0.0:3021 --upstream ch-01-02:8123;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create ch-01-02-sync --listen 0.0.0.0:3022 --upstream ch-01-02:9000;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create ch-02-01-cl --listen 0.0.0.0:3023 --upstream ch-02-01:8123;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create ch-02-01-sync --listen 0.0.0.0:3024 --upstream ch-02-01:9000;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create ch-02-02-cl --listen 0.0.0.0:3025 --upstream ch-02-02:8123;
      /go/bin/toxiproxy-cli -h toxiproxy:8474 create ch-02-02-sync --listen 0.0.0.0:3026 --upstream ch-02-02:9000;"
