services:
  chproxy:
    image: tacyuuhon/clickhouse-chproxy:latest
    ports:
      - 9050:9090
    volumes:
      - ./chproxy/config.yml:/opt/config.yml:ro
    depends_on:
      - ch-01-01
      - ch-01-02
      - ch-02-01
      - ch-02-02

  zookeeper-1:
    image: zookeeper:3.5
    restart: "unless-stopped"
    hostname: zookeeper-1
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=toxiproxy:3014:3015;3013 server.3=toxiproxy:3017:3018;3016
    healthcheck:
      test: nc -z localhost 2181 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10

  zookeeper-2:
    image: zookeeper:3.5
    restart: "unless-stopped"
    hostname: zookeeper-2
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=toxiproxy:3011:3012;3010 server.2=zookeeper-2:2888:3888;2181 server.3=toxiproxy:3017:3018;3016
    healthcheck:
      test: nc -z localhost 2181 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10

  zookeeper-3:
    image: zookeeper:3.5
    restart: "unless-stopped"
    hostname: zookeeper-3
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=toxiproxy:3011:3012;3010 server.2=toxiproxy:3014:3015;3013 server.3=zookeeper-3:2888:3888;2181
    healthcheck:
      test: nc -z localhost 2181 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10

  ch-01-01:
    image: yandex/clickhouse-server:21.4.5-alpine
    hostname: ch-01-01
    volumes:
      - ./data/clickhouse/ch-01-01/:/var/lib/clickhouse
      - ./clickhouse/initdb.d/:/docker-entrypoint-initdb.d:ro
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml:ro
      - ./clickhouse/config.d/ch-01-01.xml:/etc/clickhouse-server/config.d/node-config.xml:ro
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  ch-01-02:
    image: yandex/clickhouse-server:21.4.5-alpine
    hostname: ch-01-02
    volumes:
      - ./data/clickhouse/ch-01-02/:/var/lib/clickhouse
      - ./clickhouse/initdb.d/:/docker-entrypoint-initdb.d:ro
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml:ro
      - ./clickhouse/config.d/ch-01-02.xml:/etc/clickhouse-server/config.d/node-config.xml:ro
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  ch-02-01:
    image: yandex/clickhouse-server:21.4.5-alpine
    hostname: ch-02-01
    volumes:
      - ./data/clickhouse/ch-02-01/:/var/lib/clickhouse
      - ./clickhouse/initdb.d/:/docker-entrypoint-initdb.d:ro
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml:ro
      - ./clickhouse/config.d/ch-02-01.xml:/etc/clickhouse-server/config.d/node-config.xml:ro
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  ch-02-02:
    image: yandex/clickhouse-server:21.4.5-alpine
    hostname: ch-02-02
    volumes:
      - ./data/clickhouse/ch-02-02/:/var/lib/clickhouse
      - ./clickhouse/initdb.d/:/docker-entrypoint-initdb.d:ro
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml:ro
      - ./clickhouse/config.d/ch-02-02.xml:/etc/clickhouse-server/config.d/node-config.xml:ro
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  toxiproxy:
    container_name: toxiproxy
    restart: unless-stopped
    image: ghcr.io/shopify/toxiproxy
    command: "-host 0.0.0.0 -config /opt/toxiproxy/config.json"
    volumes:
      - ./toxiproxy/config.json:/opt/toxiproxy/config.json:ro
    ports:
      - "8474:8474"
